# Generated by Django 6.0.2 on 2026-06-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_capture_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
